package br.edu.leonardo.jaf_teste_03_iot_mqtt;

import br.edu.leonardo.jaf.sensors.BooleanSensorValue;
import br.edu.leonardo.jaf.sensors.SingleSensorValue;
import java.awt.Color;

/**
 * The main window of this application.
 * 
 * @author Leonardo Vianna do Nascimento (lvianna@gmail.com)
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnParkAlpha = new javax.swing.JPanel();
        lblParkAlphaPhoto = new javax.swing.JLabel();
        lblParkAlphaTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblParkAlphaTemp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblParkAlphaHumidity = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblParkAlphaContact1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblParkAlphaContact2 = new javax.swing.JLabel();
        pnParkAlpha1 = new javax.swing.JPanel();
        lblParkAlphaPhoto1 = new javax.swing.JLabel();
        lblParkAlphaTitle1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblParkBetaTemp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblParkBetaHumidity = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblParkBetaContact1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblParkBetaContact2 = new javax.swing.JLabel();
        pnParkAlpha2 = new javax.swing.JPanel();
        lblParkAlphaPhoto2 = new javax.swing.JLabel();
        lblParkAlphaTitle2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblDowntownTemp = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblDowntownHumidity = new javax.swing.JLabel();
        pnParkAlpha3 = new javax.swing.JPanel();
        lblParkAlphaTitle3 = new javax.swing.JLabel();
        pnParkingSpace1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnParkingSpace2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnParkingSpace3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pnParkingSpace4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnParkingSpace5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnParkingSpace6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pnParkingSpace7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Technopolis");

        pnParkAlpha.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblParkAlphaPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/leonardo/jaf_teste_03_iot_mqtt/park-alpha.jpg"))); // NOI18N
        lblParkAlphaPhoto.setMaximumSize(new java.awt.Dimension(320, 239));
        lblParkAlphaPhoto.setMinimumSize(new java.awt.Dimension(320, 239));
        lblParkAlphaPhoto.setName(""); // NOI18N
        lblParkAlphaPhoto.setPreferredSize(new java.awt.Dimension(160, 120));
        lblParkAlphaPhoto.setRequestFocusEnabled(false);

        lblParkAlphaTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblParkAlphaTitle.setText("Parque Alpha");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Temperatura:");

        lblParkAlphaTemp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParkAlphaTemp.setText("-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Umidade Relativa:");

        lblParkAlphaHumidity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParkAlphaHumidity.setText("-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Contato 1:");

        lblParkAlphaContact1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParkAlphaContact1.setText("-");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Contato 2:");

        lblParkAlphaContact2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParkAlphaContact2.setText("-");

        javax.swing.GroupLayout pnParkAlphaLayout = new javax.swing.GroupLayout(pnParkAlpha);
        pnParkAlpha.setLayout(pnParkAlphaLayout);
        pnParkAlphaLayout.setHorizontalGroup(
            pnParkAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkAlphaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParkAlphaPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnParkAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnParkAlphaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblParkAlphaTitle))
                    .addGroup(pnParkAlphaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnParkAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnParkAlphaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblParkAlphaHumidity))
                            .addGroup(pnParkAlphaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblParkAlphaTemp))
                            .addGroup(pnParkAlphaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblParkAlphaContact1))
                            .addGroup(pnParkAlphaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblParkAlphaContact2)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnParkAlphaLayout.setVerticalGroup(
            pnParkAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkAlphaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnParkAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnParkAlphaLayout.createSequentialGroup()
                        .addComponent(lblParkAlphaTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnParkAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblParkAlphaTemp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnParkAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblParkAlphaHumidity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnParkAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblParkAlphaContact1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnParkAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblParkAlphaContact2)))
                    .addComponent(lblParkAlphaPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnParkAlpha1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblParkAlphaPhoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/leonardo/jaf_teste_03_iot_mqtt/park-beta.jpg"))); // NOI18N
        lblParkAlphaPhoto1.setMaximumSize(new java.awt.Dimension(320, 239));
        lblParkAlphaPhoto1.setMinimumSize(new java.awt.Dimension(320, 239));
        lblParkAlphaPhoto1.setName(""); // NOI18N
        lblParkAlphaPhoto1.setRequestFocusEnabled(false);

        lblParkAlphaTitle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblParkAlphaTitle1.setText("Parque Beta");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Temperatura:");

        lblParkBetaTemp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParkBetaTemp.setText("-");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Umidade Relativa:");

        lblParkBetaHumidity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParkBetaHumidity.setText("-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Contato 1:");

        lblParkBetaContact1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParkBetaContact1.setText("-");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Contato 2:");

        lblParkBetaContact2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblParkBetaContact2.setText("-");

        javax.swing.GroupLayout pnParkAlpha1Layout = new javax.swing.GroupLayout(pnParkAlpha1);
        pnParkAlpha1.setLayout(pnParkAlpha1Layout);
        pnParkAlpha1Layout.setHorizontalGroup(
            pnParkAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkAlpha1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParkAlphaPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnParkAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnParkAlpha1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblParkAlphaTitle1))
                    .addGroup(pnParkAlpha1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnParkAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnParkAlpha1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblParkBetaHumidity))
                            .addGroup(pnParkAlpha1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblParkBetaTemp))
                            .addGroup(pnParkAlpha1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblParkBetaContact1))
                            .addGroup(pnParkAlpha1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblParkBetaContact2)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnParkAlpha1Layout.setVerticalGroup(
            pnParkAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkAlpha1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnParkAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnParkAlpha1Layout.createSequentialGroup()
                        .addComponent(lblParkAlphaTitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnParkAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblParkBetaTemp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnParkAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblParkBetaHumidity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnParkAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblParkBetaContact1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnParkAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblParkBetaContact2)))
                    .addComponent(lblParkAlphaPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnParkAlpha2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblParkAlphaPhoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/leonardo/jaf_teste_03_iot_mqtt/downtown.jpg"))); // NOI18N
        lblParkAlphaPhoto2.setMaximumSize(new java.awt.Dimension(320, 239));
        lblParkAlphaPhoto2.setMinimumSize(new java.awt.Dimension(320, 239));
        lblParkAlphaPhoto2.setName(""); // NOI18N
        lblParkAlphaPhoto2.setRequestFocusEnabled(false);

        lblParkAlphaTitle2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblParkAlphaTitle2.setText("Centro ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Temperatura:");

        lblDowntownTemp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDowntownTemp.setText("-");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Umidade Relativa:");

        lblDowntownHumidity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDowntownHumidity.setText("-");

        javax.swing.GroupLayout pnParkAlpha2Layout = new javax.swing.GroupLayout(pnParkAlpha2);
        pnParkAlpha2.setLayout(pnParkAlpha2Layout);
        pnParkAlpha2Layout.setHorizontalGroup(
            pnParkAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkAlpha2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParkAlphaPhoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnParkAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnParkAlpha2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblParkAlphaTitle2))
                    .addGroup(pnParkAlpha2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnParkAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnParkAlpha2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDowntownHumidity))
                            .addGroup(pnParkAlpha2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDowntownTemp)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnParkAlpha2Layout.setVerticalGroup(
            pnParkAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkAlpha2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnParkAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnParkAlpha2Layout.createSequentialGroup()
                        .addComponent(lblParkAlphaTitle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnParkAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblDowntownTemp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnParkAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblDowntownHumidity)))
                    .addComponent(lblParkAlphaPhoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnParkAlpha3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblParkAlphaTitle3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblParkAlphaTitle3.setText("Estacionamento Central");

        pnParkingSpace1.setBackground(new java.awt.Color(102, 102, 255));
        pnParkingSpace1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Vaga 1");

        javax.swing.GroupLayout pnParkingSpace1Layout = new javax.swing.GroupLayout(pnParkingSpace1);
        pnParkingSpace1.setLayout(pnParkingSpace1Layout);
        pnParkingSpace1Layout.setHorizontalGroup(
            pnParkingSpace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkingSpace1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnParkingSpace1Layout.setVerticalGroup(
            pnParkingSpace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnParkingSpace1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        pnParkingSpace2.setBackground(new java.awt.Color(102, 102, 255));
        pnParkingSpace2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Vaga 2");

        javax.swing.GroupLayout pnParkingSpace2Layout = new javax.swing.GroupLayout(pnParkingSpace2);
        pnParkingSpace2.setLayout(pnParkingSpace2Layout);
        pnParkingSpace2Layout.setHorizontalGroup(
            pnParkingSpace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkingSpace2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnParkingSpace2Layout.setVerticalGroup(
            pnParkingSpace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnParkingSpace2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        pnParkingSpace3.setBackground(new java.awt.Color(102, 102, 255));
        pnParkingSpace3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Vaga 3");

        javax.swing.GroupLayout pnParkingSpace3Layout = new javax.swing.GroupLayout(pnParkingSpace3);
        pnParkingSpace3.setLayout(pnParkingSpace3Layout);
        pnParkingSpace3Layout.setHorizontalGroup(
            pnParkingSpace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkingSpace3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnParkingSpace3Layout.setVerticalGroup(
            pnParkingSpace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnParkingSpace3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        pnParkingSpace4.setBackground(new java.awt.Color(102, 102, 255));
        pnParkingSpace4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Vaga 4");

        javax.swing.GroupLayout pnParkingSpace4Layout = new javax.swing.GroupLayout(pnParkingSpace4);
        pnParkingSpace4.setLayout(pnParkingSpace4Layout);
        pnParkingSpace4Layout.setHorizontalGroup(
            pnParkingSpace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkingSpace4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnParkingSpace4Layout.setVerticalGroup(
            pnParkingSpace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnParkingSpace4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        pnParkingSpace5.setBackground(new java.awt.Color(102, 102, 255));
        pnParkingSpace5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Vaga 5");

        javax.swing.GroupLayout pnParkingSpace5Layout = new javax.swing.GroupLayout(pnParkingSpace5);
        pnParkingSpace5.setLayout(pnParkingSpace5Layout);
        pnParkingSpace5Layout.setHorizontalGroup(
            pnParkingSpace5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkingSpace5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnParkingSpace5Layout.setVerticalGroup(
            pnParkingSpace5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnParkingSpace5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        pnParkingSpace6.setBackground(new java.awt.Color(102, 102, 255));
        pnParkingSpace6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Vaga 6");

        javax.swing.GroupLayout pnParkingSpace6Layout = new javax.swing.GroupLayout(pnParkingSpace6);
        pnParkingSpace6.setLayout(pnParkingSpace6Layout);
        pnParkingSpace6Layout.setHorizontalGroup(
            pnParkingSpace6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkingSpace6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnParkingSpace6Layout.setVerticalGroup(
            pnParkingSpace6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnParkingSpace6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        pnParkingSpace7.setBackground(new java.awt.Color(102, 102, 255));
        pnParkingSpace7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Vaga 7");

        javax.swing.GroupLayout pnParkingSpace7Layout = new javax.swing.GroupLayout(pnParkingSpace7);
        pnParkingSpace7.setLayout(pnParkingSpace7Layout);
        pnParkingSpace7Layout.setHorizontalGroup(
            pnParkingSpace7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkingSpace7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnParkingSpace7Layout.setVerticalGroup(
            pnParkingSpace7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnParkingSpace7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnParkAlpha3Layout = new javax.swing.GroupLayout(pnParkAlpha3);
        pnParkAlpha3.setLayout(pnParkAlpha3Layout);
        pnParkAlpha3Layout.setHorizontalGroup(
            pnParkAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkAlpha3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnParkAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblParkAlphaTitle3)
                    .addGroup(pnParkAlpha3Layout.createSequentialGroup()
                        .addComponent(pnParkingSpace2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnParkingSpace4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnParkingSpace6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnParkAlpha3Layout.createSequentialGroup()
                        .addComponent(pnParkingSpace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnParkingSpace3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnParkingSpace5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnParkingSpace7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnParkAlpha3Layout.setVerticalGroup(
            pnParkAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParkAlpha3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParkAlphaTitle3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParkAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnParkingSpace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnParkingSpace3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnParkingSpace5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnParkingSpace7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParkAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnParkingSpace2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnParkingSpace4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnParkingSpace6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnParkAlpha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnParkAlpha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnParkAlpha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnParkAlpha3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnParkAlpha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnParkAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnParkAlpha3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnParkAlpha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDowntownHumidity;
    private javax.swing.JLabel lblDowntownTemp;
    private javax.swing.JLabel lblParkAlphaContact1;
    private javax.swing.JLabel lblParkAlphaContact2;
    private javax.swing.JLabel lblParkAlphaHumidity;
    private javax.swing.JLabel lblParkAlphaPhoto;
    private javax.swing.JLabel lblParkAlphaPhoto1;
    private javax.swing.JLabel lblParkAlphaPhoto2;
    private javax.swing.JLabel lblParkAlphaTemp;
    private javax.swing.JLabel lblParkAlphaTitle;
    private javax.swing.JLabel lblParkAlphaTitle1;
    private javax.swing.JLabel lblParkAlphaTitle2;
    private javax.swing.JLabel lblParkAlphaTitle3;
    private javax.swing.JLabel lblParkBetaContact1;
    private javax.swing.JLabel lblParkBetaContact2;
    private javax.swing.JLabel lblParkBetaHumidity;
    private javax.swing.JLabel lblParkBetaTemp;
    private javax.swing.JPanel pnParkAlpha;
    private javax.swing.JPanel pnParkAlpha1;
    private javax.swing.JPanel pnParkAlpha2;
    private javax.swing.JPanel pnParkAlpha3;
    private javax.swing.JPanel pnParkingSpace1;
    private javax.swing.JPanel pnParkingSpace10;
    private javax.swing.JPanel pnParkingSpace11;
    private javax.swing.JPanel pnParkingSpace12;
    private javax.swing.JPanel pnParkingSpace13;
    private javax.swing.JPanel pnParkingSpace14;
    private javax.swing.JPanel pnParkingSpace2;
    private javax.swing.JPanel pnParkingSpace3;
    private javax.swing.JPanel pnParkingSpace4;
    private javax.swing.JPanel pnParkingSpace5;
    private javax.swing.JPanel pnParkingSpace6;
    private javax.swing.JPanel pnParkingSpace7;
    private javax.swing.JPanel pnParkingSpace8;
    private javax.swing.JPanel pnParkingSpace9;
    // End of variables declaration//GEN-END:variables

    /**
     * Ths method updates the information related to alpha park.
     * 
     * @param value The information obtained from alpha park sensors.
     */
    public void updateAlphaParkInfo(KhompNITZSensorValue value) {
        lblParkAlphaTemp.setText(value.getTemperature().toString());
        lblParkAlphaHumidity.setText(value.getHumidity().toString());
        lblParkAlphaContact1.setText(value.getSwitcher1().isOn() ? "Aberto" : "Fechado");
        lblParkAlphaContact2.setText(value.getSwitcher2().isOn() ? "Aberto" : "Fechado");
    }

    /**
     * Ths method updates the information related to beta park.
     * 
     * @param value The information obtained from beta park sensors.
     */
    public void updateBetaParkInfo(KhompNITZSensorValue value) {
        lblParkBetaTemp.setText(value.getTemperature().toString());
        lblParkBetaHumidity.setText(value.getHumidity().toString());
        lblParkBetaContact1.setText(value.getSwitcher1().isOn() ? "Aberto" : "Fechado");
        lblParkBetaContact2.setText(value.getSwitcher2().isOn() ? "Aberto" : "Fechado");
    }

    /**
     * Ths method updates the downtown humidity information.
     * 
     * @param value The downtown humidity value.
     */
    public void updateDowntownTemp(SingleSensorValue value) {
        lblDowntownTemp.setText(value.getValue().toString());
    }
    
    /**
     * Ths method updates the downtown temperature information.
     * 
     * @param value The downtown temperature value.
     */
    public void updateDowntownHumidity(SingleSensorValue value) {
        lblDowntownHumidity.setText(value.getValue().toString());
    }
    
    /**
     * This method updates a parking space state in the window.
     * 
     * @param spaceNo The number of the parking space.
     * @param value The state value of the parking space.
     */
    public void updateParkingSpaceState(int spaceNo, BooleanSensorValue value) {
        switch(spaceNo) {
            case 1: pnParkingSpace1.setBackground(value.isValue() ? COLOR_OFF : COLOR_ON); break;
            case 2: pnParkingSpace2.setBackground(value.isValue() ? COLOR_OFF : COLOR_ON); break;
            case 3: pnParkingSpace3.setBackground(value.isValue() ? COLOR_OFF : COLOR_ON); break;
            case 4: pnParkingSpace4.setBackground(value.isValue() ? COLOR_OFF : COLOR_ON); break;
            case 5: pnParkingSpace5.setBackground(value.isValue() ? COLOR_OFF : COLOR_ON); break;
            case 6: pnParkingSpace6.setBackground(value.isValue() ? COLOR_OFF : COLOR_ON); break;
            case 7: pnParkingSpace7.setBackground(value.isValue() ? COLOR_OFF : COLOR_ON); break;
        }
    }
    
    /**
     * The color of parking space widget when the parking space is available.
     */
    private static final Color COLOR_ON = new Color(102,102,255);
    
    /**
     * The color of parking space widget when the parking space is not available.
     */
    private static final Color COLOR_OFF = new Color(255,0,0);
}
