package br.edu.leonardo.jaf.sensors;

/**
 * A value generated by a sensor that contains a boolean value.
 * 
 * @author Leonardo Vianna do Nascimento
 */
public class BooleanSensorValue implements SensorValue {
    
    ///////////////////////////////////////////////////////////////////////////////////////////////
    // P U B L I C   C O N S T A N T S
    ///////////////////////////////////////////////////////////////////////////////////////////////
    
    /**
     * Sensor value for FALSE boolean value.
     */
    public static final BooleanSensorValue FALSE = new BooleanSensorValue(false);
    
    /**
     * Sensor value for TRUE boolean value.
     */
    public static final BooleanSensorValue TRUE = new BooleanSensorValue(true);
   
    ///////////////////////////////////////////////////////////////////////////////////////////////
    // G E T T E R S   A N D   S E T T E R S
    ///////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * This method obtains the internal value of this sensor value.
     * 
     * @return The value. 
     */
    public boolean isValue() {
        return value;
    }
    
    ///////////////////////////////////////////////////////////////////////////////////////////////
    // P R I V A T E   C O N S T R U C T O R S
    ///////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * This constructor builds a new BooleanSensorValue with the given value.
     * 
     * @param value The value for this object. 
     */
    private BooleanSensorValue(boolean value) {
        this.value = value;
    }
    
    ///////////////////////////////////////////////////////////////////////////////////////////////
    // P R I V A T E   A T T R I B U T E S
    ///////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * The value of this object.
     */
    private final boolean value;
}
