package br.edu.leonardo.jaf.sensors;

import javax.measure.Quantity;
import javax.measure.Unit;

import tec.units.ri.quantity.Quantities;

/**
 * A value generated by a sensor that contains location data: latitude, longitude, and altitude.
 */
public class LocationSensorValue implements SensorValue {

    ///////////////////////////////////////////////////////////////////////////////////////////////
    // P U B L I C   C O N S T R U C T O R S
    ///////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * This constructor builds a bew LocationSensorValue with the three given Quantity values for
     * latitude, longitude, and altitude.
     *
     * @param latitude The Quantity value for latitude.
     * @param longitude The Quantity value for longitude.
     * @param altitude The Quantity value for altitude.
     */
    public LocationSensorValue(Quantity latitude, Quantity longitude, Quantity altitude) {
        this.latitude = latitude;
        this.longitude = longitude;
        this.altitude = altitude;
    }

    /**
     * This constructor builds a bew LocationSensorValue with the three given double values for
     * latitude, longitude, and altitude. The latitude and longitude values are measured using the
     * unit specified in the latlonUnit argument, while altitude value is measured using the unit
     * specified in the altUnit argument.
     *
     * @param latitude The double value for latitude.
     * @param longitude The double value for longitude.
     * @param altitude The double value for altitude.
     * @param latlonUnit The unit used for latitude and longitude values.
     * @param altUnit The unit used for altitude value.
     */
    public LocationSensorValue(double latitude, double longitude, double altitude, Unit latlonUnit, Unit altUnit) {
        this.latitude = Quantities.getQuantity(latitude, latlonUnit);
        this.longitude = Quantities.getQuantity(longitude, latlonUnit);
        this.altitude = Quantities.getQuantity(altitude, altUnit);
    }

    ///////////////////////////////////////////////////////////////////////////////////////////////
    // G E T T E R S   A N D   S E T T E R S
    ///////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * This method obtains the value stored for latitude in this object.
     *
     * @return The reference of the quantity stored in this object for latitude.
     */
    public Quantity getLatitude() {
        return latitude;
    }

    /**
     * This method obtains the value stored for longitude in this object.
     *
     * @return The reference of the quantity stored in this object for longitude.
     */
    public Quantity getLongitude() {
        return longitude;
    }

    /**
     * This method obtains the value stored for altitude in this object.
     *
     * @return The reference of the quantity stored in this object for altitude.
     */
    public Quantity getAltitude() {
        return altitude;
    }

    ///////////////////////////////////////////////////////////////////////////////////////////////
    // TOSTRING, EQUALS, HASHCODE
    ///////////////////////////////////////////////////////////////////////////////////////////////

    @Override
    public String toString() {
        return "LocationSensorValue{" + "latitude=" + latitude + ", longitude=" + longitude + ", altitude=" + altitude + '}';
    }
    
    ///////////////////////////////////////////////////////////////////////////////////////////////
    // P R I V A T E   A T T R I B U T E S
    ///////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * The quantity value stored in this object for latitude.
     */
    private final Quantity latitude;

    /**
     * The quantity value stored in this object for longitude.
     */
    private final Quantity longitude;

    /**
     * The quantity value stored in this object for altitude.
     */
    private final Quantity altitude;
}
