package br.edu.leonardo.jaf.sensors;

import javax.measure.Quantity;
import javax.measure.Unit;

import tec.units.ri.quantity.Quantities;

/**
 * A value generated by a sensor that contains a single quantity value.
 */
public class SingleSensorValue implements SensorValue {

    ///////////////////////////////////////////////////////////////////////////////////////////////
    // P U B L I C   C O N S T R U C T O R S
    ///////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * This constructor builds a new SingleSensorValue with the given quantity value.
     *
     * @param value The value to be stored in this object.
     */
    public SingleSensorValue(Quantity value) {
        this.value = value;
    }

    /**
     * This constructor builds a new SingleSensorValue with the given double value and related unit.
     *
     * @param value The double value to be stored in this object.
     * @param unit The unit related to this value.
     */
    public SingleSensorValue(double value, Unit unit) {
        this.value = Quantities.getQuantity(value, unit);
    }

    ///////////////////////////////////////////////////////////////////////////////////////////////
    // G E T T E R S   A N D   S E T T E R S
    ///////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * This method obtains the value stored in this object.
     *
     * @return The reference of the quantity stored in this object.
     */
    public Quantity getValue() {
        return value;
    }
    
    ///////////////////////////////////////////////////////////////////////////////////////////////
    // TOSTRING, EQUALS, HASHCODE
    ///////////////////////////////////////////////////////////////////////////////////////////////

    @Override
    public String toString() {
        return "SingleSensorValue{" + "value=" + value + '}';
    }

    ///////////////////////////////////////////////////////////////////////////////////////////////
    // P R I V A T E   A T T R I B U T E S
    ///////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * The quantity value stored in this object.
     */
    private final Quantity value;
}
